// Users
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const USER_PROFILE_SUCCESS = 'USER_PROFILE_SUCCESS';

// Widgets
export const GET_WIDGETS_SUCCESS = 'GET_WIDGETS_SUCCESS';
export const DELETE_WIDGET_SUCCESS = 'DELETE_WIDGET_SUCCESS';

// Search Layout
export const LOAD_SEARCH_LAYOUT = 'LOAD_SEARCH_LAYOUT';

// MAP
export const GET_MO_SUCCESS = 'GET_MO_SUCCESS';
export const GET_MARKERS_SUCCESS = 'GET_MARKERS_SUCCESS';

// Counter MongoDB
export const GET_COUNTER_REQUEST  = 'GET_COUNTER_REQUEST';
export const GET_COUNTER_SUCCESS  = 'GET_COUNTER_SUCCESS';
export const GET_COUNTER_FAILTURE = 'GET_COUNTER_FAILTURE';

// Map MongoDB
export const GET_MAP_REQUEST   = 'GET_MAP_REQUEST';
export const GET_MAP_SUCCESS   = 'GET_MAP_SUCCESS';
export const GET_MAP_FAILTURE  = 'GET_MAP_FAILTURE';
// события по появлению /изчезновению слайдеров
export const TOOGLE_LEFT_SLIDER  = 'TOOGLE_LEFT_SLIDER';
export const TOOGLE_RIGHT_SLIDER  =  'TOOGLE_RIGHT_SLIDER';
